### ISSUE TITLE
Anticrux Javascript UCI et WinBoard 4.8.0 avec Windows 7 SP1

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/anticrux#3]
Salut erucru,

excuse-moi, mais de quelle manière fonctionne l´implémentation **Anticrucx UCI Javascript** avec le logiciel **Javascript Universal Chess Interface** https://sourceforge.net/projects/jsuci/ comme Lozza JS dans le cadre **WinBoard 4.8.0** http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=51528

Quelles informations nécessaires doivent contenir les articles suivants?

engine (.exe or .jar): __________________________
commandline-line parameters:________________________
WinBoard options:____________________________

> l´option UCI

**AntiChess = variante des échecs losers, giveaway ou suicide ?**

J´ai mentionné Anticrux dans la collection **CCWiki ici**:
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:variants_engine_list (>Losing Chess/Suicide Chess)

l´auteur de Lozza Javascript UCI , Colin Jenkins, (dans le pays de Galles = Wales)a écrit dans langue anglaise: cf. https://chessprogramming.wikispaces.com/Lozza

**Lozza Javascript - UCI**

Download the latest jsUCI  http://sourceforge.net/projects/jsuci/files/ ,  Unzip into a folder of your choice.
Download lozza.js http://op12no2.me/toys/lozza/lozza.js (right-click the link and use “save link as” or something like, that dependent on your browser) and save into the same folder.
Create a new engine in your favourite chess UI.  The executable will be jsuci_1_2.exe and the parameter it needs is lozza.js.  Select UCI protocol.
You can also run Lozza from a command line:-

jsuci_1_2.exe lozza.js
NOTES

The image at the top of the post can be used as a logo :)
Like running in a browser, Lozza is being compiled and optimised in real time under jsUCI (V8) and performance will never be as good as a native executable.
The jsUCI executable file name may change as new versions are added.
Lozza needs an explicit ucinewgame.
Lozza cannot ponder or stop an analysis, but chess UIs usually have a way to restart an engine which can be used to terminate analysis.
 lozza.js is updated frequently.  Check the change history for progress.

**Comment by ecrucru** [comment]
Hello @yellow-panther

_(I reply in English to be well understood by other people)_

**1) jsUCI**

AntiCrux Engine UCI works through NodeJS only. In Lozza's source code, there is a distinction between NodeJS and jsUCI which means that the technical implementation is slightly different. So there is no existing support for jsUCI at the current time and this could be a future enhancement.

WinBoard 4.8.0b is compatible with AntiCrux when this one is ran as an Internet chess server (aka. "[AntiCrux Server](https://github.com/ecrucru/anticrux/blob/master/README.md#anticrux-server)"). It is uncommon but compared to the UCI interface, there are enhanced features to send messages, count the victories, show the news, etc...

**2) Parameters**

AntiCrux Engine UCI is not fully supported for WinBoard yet because the user interaction has some problems not encountered with [pyChess](https://github.com/ecrucru/anticrux/blob/master/README.md#procedure-for-pychess). This is a topic in progress. Once you have installed NodeJS, you should add the following entry in WinBoard's list of engines :

```
"AntiCrux" -fcp "C:\nodejs\node.exe --expose-gc C:\anticrux\anticrux-engine.js" -fd "C:\anticrux" -fn "AntiCrux" /fUCI /variant=suicide
```

From a general point of view, you have these settings for AntiCrux Engine UCI :
- Engine : `node.exe`
- Arguments : `--expose-gc "C:\anticrux\anticrux-engine.js"`
- WinBoard options : refer above

**3) Variant name**

"antichess" is the name used on lichess.org and some other websites. When looking at the source code, it corresponds to "[giveaway](https://github.com/ornicar/lila/blob/master/ui/ceval/src/stockfishProtocol.ts#L29)" but I declared AntiCrux to react to "[suicide](http://www.freechess.org/Help/HelpFiles/suicide_chess.html)" because castling is [not supported](https://github.com/ddugovic/Stockfish/blob/master/src/uci.cpp#L73). The term "suicide" has the same meaning in WinBoard and pyChess.

If you send `uci` to AntiCrux Engine UCI, it will return the supported values :

```
option name UCI_Variant type combo default suicide var suicide
```

**4) Further processing**

Thanks a lot for having mentioned my engine in your wiki :-)

I keep the issue opened to fix :

- the compatibility with WinBoard through UCI (bug)
- jsUCI (enhancement)

Thank you.

**Comment by ecrucru** [comment]
@yellow-panther : after this little update, you can use AntiCrux with WinBoard through NodeJS
https://github.com/ecrucru/anticrux/blob/master/README.md#procedure-for-winboard

jsUCI is still under investigation.

**Comment by ecrucru** [comment]
Please refer to the issue #4 for a detailed reply about jsUCI.
