### ISSUE TITLE
Anticrux with Node.JS and WinBoard AA beta

### ISSUE THREAD

**Issue by yellow-panther** [ecrucru/anticrux#5]
Hello ecrcru,

I have installed **nodeJS** on C:\Program Files\nodejs\node.exe
AnticruxJS is on C:\Users\NRL\Downloads\anticrux-master\anticrux-master\anticrux-engine.js

you said:
"AntiCrux" -fcp "C:\fullpath\nodejs\node.exe --expose-gc C:\fullpath\anticrux-engine.js" -fd "C:\fullpath\anticrux" -fn "AntiCrux" -fUCI /variant=suicide

Well, that is for me (only a user, not a programmer) these things are a little bit obfuscated

What data have to be inserted into the rows  of WinBoard AA beta here=

jar or exe :
commandline-parameters:
WinBoard potions:

Is --expose-gc synonymous with garbage colection e.g. https://github.com/SocketCluster/socketcluster/issues/105 ?

What other  variants -except of Suicide Chess- are supported by Anticrux-engine respectively can these applications be used now with Edmund´s Javascript UCI - or is node.js in each case necessary?

What UCI option have to be invoked? UCI or UCCI/USI/Arena960

If for Anticrux would exist a CECP a.k.a. WinBoard* compatible edition, implementation will be much easier than this procedure, even with older WinBoard GUI versions.
* v1 http://home.hccnet.nl/h.g.muller/engine-intf.html 
* v2 http://hgm.nubati.net/CECP.html 

Did you receive my message in French some days ago via http://ecrucru.free.fr/?page=contact&ref=anticrux - I could not regognize a confirmation like "mesage envoyé" or something else.

What´s about Scidb by Gregor Cramer http://scidb.sourceforge.net/index.html ?

**Comment by ecrucru** [comment]
Hello @yellow-panther,

**1)** The provided command line is how data is saved at the end into WinBoard and you just need to change the paths. In fact, you probably want to use the GUI to add the engine "field by field". So the equivalent mapping is :

- Nickname : `AntiCrux`
- Engine : `"C:\full-path-to-nodejs\node.exe"`
- Command-line parameters : `--expose-gc "C:\fullpath-to-anticrux\anticrux-engine.js"`
- Special WinBoard options : `/variant=suicide`
- Directory : `C:\fullpath-to-anticrux\`
- [x] UCI
- [X] Add this engine to the list

Don't forget to download the latest master released last evening.

**2)** Yes, `--expose-gc` is for the garbage collector. It has little influence but it is recommended to activate this option.

**3)** NodeJS is the sole supported host application. Refer to #3 and #4 for the news about your recent request.

**4)** Because you can now use AntiCrux Engine UCI with WinBoard 4.9 and NodeJS, there is no major requirement to think about the implementation of the WB protocol to circumvent the previous issues principally caused by WinBoard itself.

**5)** I have not received your message. It has not been submitted at all.

**6)** SciDB is yet another GUI. If you want to use it, the settings should be similar.

I let you confirm that everything is fine with the configuration.

Regards

**Comment by ecrucru** [comment]
**1)** The procedure for WinBoard has been updated :
https://github.com/ecrucru/anticrux/blob/master/README.md#procedure-for-winboard
